### ISSUE TITLE
Import external homes from other plugins

### ISSUE THREAD

**Issue by FrancescoJacovo** [Banarnia-Services/FancyHomes#1]
Can u auto-import essentials-home and add the custom-model-data option for owned-home and another one for no-permission-home?

**Comment by MikeNipkow** [comment]
Added a command to import existing homes from essentials. Will not override existing homes with the same name:
<img width="350" alt="image" src="https://github.com/Banarnia-Services/FancyHomes/assets/107308614/07f6371e-8fbc-46ec-954f-1c72a4d81c30">

Will be implemented in release 1.2.

Don't exactly know what you mean with the custom-model-data option. If you need it please clarify.

**Comment by FrancescoJacovo** [comment]
Like the origin-realms server: you have a homes gui with 54 size and in every slot u see a lock "locked" and "unlocked" to represent the homes that the specific player have, can set and cannot set because doesn't have a specific rank. They show this distinction with custom-model-data (so minecraft custom textured) and lores!

**Comment by FrancescoJacovo** [comment]
Cool for the import but i was talking about a sync with essentials in real-time
