### ISSUE TITLE
Block Cheating 

### ISSUE THREAD

**Issue by NoxesTv** [Banarnia-Services/FancyHomes#3]
Hy, I Installed your Plugin on my Server... 
In the Deleting section you can pull out the Emerald und Redstone Block out of the Prompt and Place it. 
is it possible to fix and Update this? 

Best regards.

**Comment by MikeNipkow** [comment]
Hey,
is there an error message in the console? Could you provide the logs, I will look into it tomorrow.

**Comment by NoxesTv** [comment]
no no error in the console, we found it by testing multiple plugins on my Server.  A Friend tryed to pull out items in the Deleting Menu, and he get it.

**Comment by NoxesTv** [comment]
is there a way to  fix this or change the Emerald and Redstone block to Red and Green Dye ?

**Comment by MikeNipkow** [comment]
Yes I will fix this tomorrow and provide a new Version. Did you do anything specific to reproduce this?
Do you use the file storage or MySQL?

So far you cannot change the Icon item type.

**Comment by NoxesTv** [comment]
Thx a lot. i use the file Version.

**Comment by MikeNipkow** [comment]
I was not able to reproduce this issue in any scenario. Maybe you could provide detailed steps on how to reproduce this?
A possible cause is another interfering plugin.

Which minecraft version do you use? Which plugin version did you use so far?

Attached you can find a snapshot version 1.3.1 where I changed the behaviour after clicking anything in the confirmation gui. Please check if this solves your issue.
I also changed the material to red and green dye.

[FancyHomes-1.3.1-SNAPSHOT.jar.zip](https://github.com/Banarnia-Services/FancyHomes/files/13334338/FancyHomes-1.3.1-SNAPSHOT.jar.zip)

**Comment by NoxesTv** [comment]
Hy, 
I Updatet to version 1.3.1.
Same Problem, look @ the Picture. i Send you a serverlog. Thx for Help 

[latest.log](https://github.com/Banarnia-Services/FancyHomes/files/13335535/latest.log)
![Screenshot 2023-11-13 150411](https://github.com/Banarnia-Services/FancyHomes/assets/150619687/fb887953-51b5-4f30-a8e5-6674f38f9296)

**Comment by MikeNipkow** [comment]
Could you add me on Discord to continue debugging?: lesoap

**Comment by NoxesTv** [comment]
i added you please Contact me on Discord   NoXeS__#7212
