### ISSUE TITLE
fancyhomes.limit.<LIMIT> not honored

### ISSUE THREAD

**Issue by jnijland** [Banarnia-Services/FancyHomes#4]
According to the SpigotMC page, I can use the following permission to set the maximum of homes a player can have: 
```fancyhomes.limit.<LIMIT>: Set the home limit (requires LuckPerms)```

I've set the limit for group A on 3, for group B on 10. When having ```max-homes: 1``` in the config, both groups can have a maximum of 1 home. When I set the config option to 50, every group has the option to set 50 homes. 

I want to be able to configure the maximum amount of homes for a player based on their LuckPerms group, and this doesn't seem to work. 

Using Purpur Version: 1.21.1-2315-2a50638 (MC: 1.21.1)*
FancyHomes: 1.3.6

**Comment by MikeNipkow** [comment]
Thanks for reporting this issue.

Please check out version 1.3.7, which should fix your issue:
[https://www.spigotmc.org/resources/fancyhomes-%C2%BB-1-13-1-21-1.112762/update?update=564139](url)

Keep in mind, that you will need to add the permission as Meta-Value - not just as simple permission:
![image](https://github.com/user-attachments/assets/00da5076-d8e4-4d52-8743-3adfc298a25d)

Should look similar to this in the editor:
![image](https://github.com/user-attachments/assets/de092011-2353-4c28-b548-57b560c60b05)


Further information on LuckPerms docs:
[https://luckperms.net/wiki/Meta-Commands](url)

**Comment by MikeNipkow** [comment]
Update:
You can now just add the permission meta.fancyhomes-limit.x, when LuckPerms is installed to prevent any confusion.
