### ISSUE TITLE
home Limit 

### ISSUE THREAD

**Issue by KOKSBARON777** [Banarnia-Services/FancyHomes#6]
i cant set the limit of home in Luckperms

**Comment by MikeNipkow** [comment]
Hello @KOKSBARON777,

I copy the details of the Profile Message on SpigotMC here to clarify your setup:
```
I can't set a limit of homes for the ranks.
I have 6 ranks
default + 5 more
default should have 2 homes and the last rank a maximum of 20 homes. fancyhomes.limit.<LIMIT> for example fancyhomes.limit.2 or what should I enter for luckperms?
I can't find a <LIMIT> in the luckperms meta
it would be best if you could enter the number of homes for the individual ranks in the config
```

I know that the easiest solution would be to just set the permission fancyhomes.limit.x to configure the individual home limit. However this is not possible with a performant solution, as with every Home-Limit check (drastically spoken) the plugin would need to iterate over every permission from 1 to xxx to check if the player has a certain limit permission. Therefore this is not a proper solution.

I already clarified the correct configuration in #4. Please have a look at how to configure it properly using the LuckPerms mechanics.
I guess the permissions could be `meta.fancyhomes\.limit.20` for 20 homes. You can check if with the LuckPerms info command, which displays all Meta-Permissions, as also shown in #4.

Further details are described in the LuckPerms docs: [https://luckperms.net/wiki/Meta-Commands](https://github.com/Banarnia-Services/FancyHomes/issues/url)
Feel free to come back to me, if you encounter any problems.

Also keep in mind to use the latest FancyHomes-Release, as you didn't mention the version you are using.

**Comment by MikeNipkow** [comment]
Update:
You can now just add the permission meta.fancyhomes-limit.x, when LuckPerms is installed to prevent any confusion.
