### ISSUE TITLE
Customize the data shown in /homes

### ISSUE THREAD

**Issue by jnijland** [Banarnia-Services/FancyHomes#7]
Currently, I am not able to change the following texts in the ```/homes (<player>)``` GUI menu:
- The date information; 
- The world information;
<img width="242" alt="image" src="https://github.com/user-attachments/assets/606556b2-1390-4102-af91-487f6eb0364b">

This is a feature request, but in my case I would actually like to disable the information provided. Maybe this could be done using the language configuration to provide a more versatile option for other users :)

**Comment by MikeNipkow** [comment]
Implemented in Version 1.3.8 on SpigotMC.
