### ISSUE TITLE
Can`t tab homes

### ISSUE THREAD

**Issue by KOKSBARON777** [Banarnia-Services/FancyHomes#8]
![image](https://github.com/user-attachments/assets/f1583b36-0935-4d79-ab72-1a6ca4775def)
I can`t tab my homes, is that normal?

**Comment by MikeNipkow** [comment]
Not able to reproduce this on my site. Perhaps you need to restart your server or update your server software?
![image](https://github.com/user-attachments/assets/70d5895c-34af-44b8-b2dd-fd38b869b65f)

**Comment by KOKSBARON777** [comment]
glaube du sprichst auch deutsch oder?
also ich kann als admin sowie als default spieler nicht die homes taben
hat das vielleicht was mit anderen permissions zutun wie essentials oder fehlt einfach eine permission von fancyhomes?
